
#Example2:Masking and passing a secret between jobs and workflows
#if you want to pass a masked secret between jobs or workflows, you should store the secret in a store and then retrieve it in subsequent job or workflow.
#setup:
#    1. Setup a secret store to store the secret that you will generate during your workflow.for ex, Vault
#    2. Generate a key for reading and writing to that secret store. Store the key as a repository secret.

