name: workflow-commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"  
      - name: setting an error message with params
        run: echo "::error tile=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Setting a debug message with params
        run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Setting a Warning with param
        run: echo "::Warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Setting a notice with param
        run: echo "::Notice title=Notice title,file=app.js,line=2,endLine=3,col=5,endColum=7::Missing Semicolon"
          
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
          echo "::group::My title"
          echo "Inside group"
          echo "::endgroup"
 #Masking an environment variable: when you print the variable MY_NAME or the value "Mona the Octocat" in the log, you'll see "****" instead of "Mona The Octocat"        
  bash-Mask-example:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "Mona The Octocat"
    steps:
      - name: bash-version
        run: echo "::add-mask::$MY_NAME"

        